[package]
name = "bagel"
version = "0.1.0"
edition = "2021"

[dependencies]
assert_cmd = "2.0.16"
assert_fs = "1.1.2"
owo-colors = "4.0.0"
predicates = "3.1.2"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
